//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enchere.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enchere.Ressource.ResourceView", typeof(ResourceView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;authentification.
        /// </summary>
        public static string autherror {
            get {
                return ResourceManager.GetString("autherror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur ou mot de passe invalide!.
        /// </summary>
        public static string autherror2 {
            get {
                return ResourceManager.GetString("autherror2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilté.
        /// </summary>
        public static string Civilté {
            get {
                return ResourceManager.GetString("Civilté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez le mot de passe: minimum 6 caractères et maximum 50!.
        /// </summary>
        public static string ConfirmezMDP {
            get {
                return ResourceManager.GetString("ConfirmezMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote.
        /// </summary>
        public static string Cote {
            get {
                return ResourceManager.GetString("Cote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créér.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        public static string Editer {
            get {
                return ResourceManager.GetString("Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiquez votre courriel.
        /// </summary>
        public static string entrerCourriel {
            get {
                return ResourceManager.GetString("entrerCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiquez votre numero.
        /// </summary>
        public static string entrerNr {
            get {
                return ResourceManager.GetString("entrerNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;inscription.
        /// </summary>
        public static string Inscription {
            get {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce n&apos;est pas le bon format de telephone!.
        /// </summary>
        public static string mauvaisformattel {
            get {
                return ResourceManager.GetString("mauvaisformattel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MDP {
            get {
                return ResourceManager.GetString("MDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe et la confirmation ne correspondent pas..
        /// </summary>
        public static string MDPCONFIRMDIFFERENT {
            get {
                return ResourceManager.GetString("MDPCONFIRMDIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit compter minimum 6 caractères et maximum 50!.
        /// </summary>
        public static string MDPminmax {
            get {
                return ResourceManager.GetString("MDPminmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe est requis.
        /// </summary>
        public static string MDPrequis {
            get {
                return ResourceManager.GetString("MDPrequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel utilisateur.
        /// </summary>
        public static string newuser {
            get {
                return ResourceManager.GetString("newuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de famille.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        public static string Numéro {
            get {
                return ResourceManager.GetString("Numéro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string Téléphone {
            get {
                return ResourceManager.GetString("Téléphone", resourceCulture);
            }
        }
    }
}
