//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enchere.Ressource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceView() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enchere.Ressource.ResourceView", typeof(ResourceView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acheter.
        /// </summary>
        public static string Acheter {
            get {
                return ResourceManager.GetString("Acheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acheteur.
        /// </summary>
        public static string Acheteur {
            get {
                return ResourceManager.GetString("Acheteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter Categorie.
        /// </summary>
        public static string AjouterCateg {
            get {
                return ResourceManager.GetString("AjouterCateg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune evaluation trouvee.
        /// </summary>
        public static string Aucuneevaluationtrouvee {
            get {
                return ResourceManager.GetString("Aucuneevaluationtrouvee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Augmentation minimale.
        /// </summary>
        public static string Augmentationminimale {
            get {
                return ResourceManager.GetString("Augmentationminimale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;authentification.
        /// </summary>
        public static string autherror {
            get {
                return ResourceManager.GetString("autherror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur ou mot de passe invalide!.
        /// </summary>
        public static string autherror2 {
            get {
                return ResourceManager.GetString("autherror2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour.
        /// </summary>
        public static string Bonjour {
            get {
                return ResourceManager.GetString("Bonjour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        public static string Catégorie {
            get {
                return ResourceManager.GetString("Catégorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer.
        /// </summary>
        public static string Changer {
            get {
                return ResourceManager.GetString("Changer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer commission.
        /// </summary>
        public static string Changercommission {
            get {
                return ResourceManager.GetString("Changercommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Civilté.
        /// </summary>
        public static string Civilté {
            get {
                return ResourceManager.GetString("Civilté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code du membre.
        /// </summary>
        public static string Codedumembre {
            get {
                return ResourceManager.GetString("Codedumembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire.
        /// </summary>
        public static string Commentaire {
            get {
                return ResourceManager.GetString("Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commission actuel.
        /// </summary>
        public static string Commissionactuel {
            get {
                return ResourceManager.GetString("Commissionactuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez le mot de passe: minimum 6 caractères et maximum 50!.
        /// </summary>
        public static string ConfirmezMDP {
            get {
                return ResourceManager.GetString("ConfirmezMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contactez nous.
        /// </summary>
        public static string Contacteznous {
            get {
                return ResourceManager.GetString("Contacteznous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cote.
        /// </summary>
        public static string Cote {
            get {
                return ResourceManager.GetString("Cote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courriel.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créér.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créér objet.
        /// </summary>
        public static string Créérobjet {
            get {
                return ResourceManager.GetString("Créérobjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Depart.
        /// </summary>
        public static string DateDepart {
            get {
                return ResourceManager.GetString("DateDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Fin.
        /// </summary>
        public static string DateFin {
            get {
                return ResourceManager.GetString("DateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à De.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deconnexion.
        /// </summary>
        public static string Deconnexion {
            get {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à De Membre.
        /// </summary>
        public static string DeMembre {
            get {
                return ResourceManager.GetString("DeMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dans les dernières 24h.
        /// </summary>
        public static string dernières24h {
            get {
                return ResourceManager.GetString("dernières24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Derniers membres inscrits.
        /// </summary>
        public static string Derniersmembresinscrits {
            get {
                return ResourceManager.GetString("Derniersmembresinscrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Derniers produits.
        /// </summary>
        public static string Derniersproduits {
            get {
                return ResourceManager.GetString("Derniersproduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Derniers Produits publiés les dernières 24h.
        /// </summary>
        public static string DerniersProduits24h {
            get {
                return ResourceManager.GetString("DerniersProduits24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Donner votre prix.
        /// </summary>
        public static string Donnervotreprix {
            get {
                return ResourceManager.GetString("Donnervotreprix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Editer {
            get {
                return ResourceManager.GetString("Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer données objet.
        /// </summary>
        public static string Editerdonnéesobjet {
            get {
                return ResourceManager.GetString("Editerdonnéesobjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer Les Informations du Membre.
        /// </summary>
        public static string EditerInformationsMembre {
            get {
                return ResourceManager.GetString("EditerInformationsMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string EditObjet {
            get {
                return ResourceManager.GetString("EditObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enchere.
        /// </summary>
        public static string Enchere {
            get {
                return ResourceManager.GetString("Enchere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encherir.
        /// </summary>
        public static string Encherir {
            get {
                return ResourceManager.GetString("Encherir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indiquez votre courriel.
        /// </summary>
        public static string entrerCourriel {
            get {
                return ResourceManager.GetString("entrerCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indiquez votre numero.
        /// </summary>
        public static string entrerNr {
            get {
                return ResourceManager.GetString("entrerNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En Vente.
        /// </summary>
        public static string EnVent {
            get {
                return ResourceManager.GetString("EnVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string Envoyer {
            get {
                return ResourceManager.GetString("Envoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous sûr de vouloir supprimer cette catégorie.
        /// </summary>
        public static string Êtesvouscatégorie {
            get {
                return ResourceManager.GetString("Êtesvouscatégorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous sûr de vouloir supprimer le compte de ce membre.
        /// </summary>
        public static string Êtesvousmembre {
            get {
                return ResourceManager.GetString("Êtesvousmembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluations du membre.
        /// </summary>
        public static string Evaluationsdumembre {
            get {
                return ResourceManager.GetString("Evaluationsdumembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion Enchères.
        /// </summary>
        public static string GestionEncheres {
            get {
                return ResourceManager.GetString("GestionEncheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des objets.
        /// </summary>
        public static string gestobj {
            get {
                return ResourceManager.GetString("gestobj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id du membre.
        /// </summary>
        public static string Iddumembre {
            get {
                return ResourceManager.GetString("Iddumembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IdMembre.
        /// </summary>
        public static string IdMembre {
            get {
                return ResourceManager.GetString("IdMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Imprimer le rapport.
        /// </summary>
        public static string Imprimerrapport {
            get {
                return ResourceManager.GetString("Imprimerrapport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;inscription.
        /// </summary>
        public static string Inscription {
            get {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Inscriptionsite {
            get {
                return ResourceManager.GetString("Inscriptionsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste Des Évaluations Des Membres.
        /// </summary>
        public static string ListeDesÉvaluationsDesMembres {
            get {
                return ResourceManager.GetString("ListeDesÉvaluationsDesMembres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des objets.
        /// </summary>
        public static string Listedesobjets {
            get {
                return ResourceManager.GetString("Listedesobjets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste Membres Inscrits.
        /// </summary>
        public static string ListeMembresInscrits {
            get {
                return ResourceManager.GetString("ListeMembresInscrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste Objets Vendus Sous Peu.
        /// </summary>
        public static string ListeObjetsVendusSousPeu {
            get {
                return ResourceManager.GetString("ListeObjetsVendusSousPeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister echères perdus.
        /// </summary>
        public static string Listerecheresperdus {
            get {
                return ResourceManager.GetString("Listerecheresperdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister enchères encherits.
        /// </summary>
        public static string Listerencheresencherits {
            get {
                return ResourceManager.GetString("Listerencheresencherits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister enchères en cours.
        /// </summary>
        public static string Listerencheresencours {
            get {
                return ResourceManager.GetString("Listerencheresencours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister mes objets vendus - pdf.
        /// </summary>
        public static string Listermesobjetsvenduspdf {
            get {
                return ResourceManager.GetString("Listermesobjetsvenduspdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister objets achetés.
        /// </summary>
        public static string Listerobjetsachetes {
            get {
                return ResourceManager.GetString("Listerobjetsachetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister objets vendus.
        /// </summary>
        public static string Listerobjetsvendus {
            get {
                return ResourceManager.GetString("Listerobjetsvendus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister produits qui m&apos;ont intéressés - pdf.
        /// </summary>
        public static string Listerproduitsinteressepdf {
            get {
                return ResourceManager.GetString("Listerproduitsinteressepdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste utilisateurs.
        /// </summary>
        public static string ListeUsers {
            get {
                return ResourceManager.GetString("ListeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce n&apos;est pas le bon format de telephone!.
        /// </summary>
        public static string mauvaisformattel {
            get {
                return ResourceManager.GetString("mauvaisformattel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier profil.
        /// </summary>
        public static string mdfprofil {
            get {
                return ResourceManager.GetString("mdfprofil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string MDP {
            get {
                return ResourceManager.GetString("MDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe et la confirmation ne correspondent pas..
        /// </summary>
        public static string MDPCONFIRMDIFFERENT {
            get {
                return ResourceManager.GetString("MDPCONFIRMDIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit compter minimum 6 caractères et maximum 50!.
        /// </summary>
        public static string MDPminmax {
            get {
                return ResourceManager.GetString("MDPminmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe est requis.
        /// </summary>
        public static string MDPrequis {
            get {
                return ResourceManager.GetString("MDPrequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes objets.
        /// </summary>
        public static string Mesobjets {
            get {
                return ResourceManager.GetString("Mesobjets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes objets en vente.
        /// </summary>
        public static string Mesobjetsenvente {
            get {
                return ResourceManager.GetString("Mesobjetsenvente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre En Vente.
        /// </summary>
        public static string MettreEnVente {
            get {
                return ResourceManager.GetString("MettreEnVente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier Informations Profil.
        /// </summary>
        public static string ModifierInformationsProfil {
            get {
                return ResourceManager.GetString("ModifierInformationsProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mot de passe.
        /// </summary>
        public static string ModifierMDP {
            get {
                return ResourceManager.GetString("ModifierMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe oublié? Envoyer nouveau mot de passe vers mon adresse courriel.
        /// </summary>
        public static string Motoublié {
            get {
                return ResourceManager.GetString("Motoublié", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvel utilisateur.
        /// </summary>
        public static string newuser {
            get {
                return ResourceManager.GetString("newuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de famille.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string nom2 {
            get {
                return ResourceManager.GetString("nom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau.
        /// </summary>
        public static string Nouveau {
            get {
                return ResourceManager.GetString("Nouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle enchère.
        /// </summary>
        public static string Nouvelenchere {
            get {
                return ResourceManager.GetString("Nouvelenchere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle categorie.
        /// </summary>
        public static string Nouvellecategorie {
            get {
                return ResourceManager.GetString("Nouvellecategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle Evaluation.
        /// </summary>
        public static string Nouvellevaluation {
            get {
                return ResourceManager.GetString("Nouvellevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro.
        /// </summary>
        public static string Numéro {
            get {
                return ResourceManager.GetString("Numéro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objets qui m&apos;ont intéressés.
        /// </summary>
        public static string Objetsintéressés {
            get {
                return ResourceManager.GetString("Objetsintéressés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page Commission.
        /// </summary>
        public static string PageCommission {
            get {
                return ResourceManager.GetString("PageCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page Rapports.
        /// </summary>
        public static string PageRapports {
            get {
                return ResourceManager.GetString("PageRapports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix.
        /// </summary>
        public static string Prix {
            get {
                return ResourceManager.GetString("Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix Actuel.
        /// </summary>
        public static string PrixActuel {
            get {
                return ResourceManager.GetString("PrixActuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix Départ.
        /// </summary>
        public static string PrixDepart {
            get {
                return ResourceManager.GetString("PrixDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix proposé.
        /// </summary>
        public static string Prixpropose {
            get {
                return ResourceManager.GetString("Prixpropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapports.
        /// </summary>
        public static string Rapports {
            get {
                return ResourceManager.GetString("Rapports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapport sur la cote des membres.
        /// </summary>
        public static string Rapportsurlacotedesmembres {
            get {
                return ResourceManager.GetString("Rapportsurlacotedesmembres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapport sur la synthese de vente annuelle.
        /// </summary>
        public static string Rapportsursynthesevente {
            get {
                return ResourceManager.GetString("Rapportsursynthesevente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Récuperation du nouveau mot de passe.
        /// </summary>
        public static string Récuperationmot {
            get {
                return ResourceManager.GetString("Récuperationmot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet.
        /// </summary>
        public static string Sujet {
            get {
                return ResourceManager.GetString("Sujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synthèse Ventes Annuelles.
        /// </summary>
        public static string SynthèseVentesAnnuelles {
            get {
                return ResourceManager.GetString("SynthèseVentesAnnuelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléchager.
        /// </summary>
        public static string Telechager {
            get {
                return ResourceManager.GetString("Telechager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à télécharger la pièce jointe.
        /// </summary>
        public static string telechargerlapiecejointe {
            get {
                return ResourceManager.GetString("telechargerlapiecejointe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        public static string Téléphone {
            get {
                return ResourceManager.GetString("Téléphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Ventes.
        /// </summary>
        public static string TotalVentes {
            get {
                return ResourceManager.GetString("TotalVentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les membres inscrits.
        /// </summary>
        public static string Touslesmembresinscrits {
            get {
                return ResourceManager.GetString("Touslesmembresinscrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vendeur.
        /// </summary>
        public static string Vendeur {
            get {
                return ResourceManager.GetString("Vendeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes echus ou sous peu echus - pdf.
        /// </summary>
        public static string Ventesechusousouspeuechuspdf {
            get {
                return ResourceManager.GetString("Ventesechusousouspeuechuspdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir Evaluation.
        /// </summary>
        public static string VoirEvaluation {
            get {
                return ResourceManager.GetString("VoirEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zone administration.
        /// </summary>
        public static string Zoneadministration {
            get {
                return ResourceManager.GetString("Zoneadministration", resourceCulture);
            }
        }
    }
}
