//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enchere.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enchere.Ressource.ResourceView", typeof(ResourceView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acheter.
        /// </summary>
        public static string Acheter {
            get {
                return ResourceManager.GetString("Acheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acheteur.
        /// </summary>
        public static string Acheteur {
            get {
                return ResourceManager.GetString("Acheteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter Categorie.
        /// </summary>
        public static string AjouterCateg {
            get {
                return ResourceManager.GetString("AjouterCateg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune evaluation trouvee.
        /// </summary>
        public static string Aucuneevaluationtrouvee {
            get {
                return ResourceManager.GetString("Aucuneevaluationtrouvee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmentation minimale.
        /// </summary>
        public static string Augmentationminimale {
            get {
                return ResourceManager.GetString("Augmentationminimale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;authentification.
        /// </summary>
        public static string autherror {
            get {
                return ResourceManager.GetString("autherror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur ou mot de passe invalide!.
        /// </summary>
        public static string autherror2 {
            get {
                return ResourceManager.GetString("autherror2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour.
        /// </summary>
        public static string Bonjour {
            get {
                return ResourceManager.GetString("Bonjour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Catégorie {
            get {
                return ResourceManager.GetString("Catégorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer.
        /// </summary>
        public static string Changer {
            get {
                return ResourceManager.GetString("Changer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer commission.
        /// </summary>
        public static string Changercommission {
            get {
                return ResourceManager.GetString("Changercommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilté.
        /// </summary>
        public static string Civilté {
            get {
                return ResourceManager.GetString("Civilté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code du membre.
        /// </summary>
        public static string Codedumembre {
            get {
                return ResourceManager.GetString("Codedumembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire.
        /// </summary>
        public static string Commentaire {
            get {
                return ResourceManager.GetString("Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission actuel.
        /// </summary>
        public static string Commissionactuel {
            get {
                return ResourceManager.GetString("Commissionactuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez le mot de passe: minimum 6 caractères et maximum 50!.
        /// </summary>
        public static string ConfirmezMDP {
            get {
                return ResourceManager.GetString("ConfirmezMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactez nous.
        /// </summary>
        public static string Contacteznous {
            get {
                return ResourceManager.GetString("Contacteznous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote.
        /// </summary>
        public static string Cote {
            get {
                return ResourceManager.GetString("Cote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créér.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créér objet.
        /// </summary>
        public static string Créérobjet {
            get {
                return ResourceManager.GetString("Créérobjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Depart.
        /// </summary>
        public static string DateDepart {
            get {
                return ResourceManager.GetString("DateDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Fin.
        /// </summary>
        public static string DateFin {
            get {
                return ResourceManager.GetString("DateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconnexion.
        /// </summary>
        public static string Deconnexion {
            get {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Membre.
        /// </summary>
        public static string DeMembre {
            get {
                return ResourceManager.GetString("DeMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans les dernières 24h.
        /// </summary>
        public static string dernières24h {
            get {
                return ResourceManager.GetString("dernières24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniers membres inscrits.
        /// </summary>
        public static string Derniersmembresinscrits {
            get {
                return ResourceManager.GetString("Derniersmembresinscrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniers produits.
        /// </summary>
        public static string Derniersproduits {
            get {
                return ResourceManager.GetString("Derniersproduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniers Produits publiés les dernières 24h.
        /// </summary>
        public static string DerniersProduits24h {
            get {
                return ResourceManager.GetString("DerniersProduits24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donner votre prix.
        /// </summary>
        public static string Donnervotreprix {
            get {
                return ResourceManager.GetString("Donnervotreprix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        public static string Editer {
            get {
                return ResourceManager.GetString("Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer données objet.
        /// </summary>
        public static string Editerdonnéesobjet {
            get {
                return ResourceManager.GetString("Editerdonnéesobjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer Les Informations du Membre.
        /// </summary>
        public static string EditerInformationsMembre {
            get {
                return ResourceManager.GetString("EditerInformationsMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string EditObjet {
            get {
                return ResourceManager.GetString("EditObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchere.
        /// </summary>
        public static string Enchere {
            get {
                return ResourceManager.GetString("Enchere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encherir.
        /// </summary>
        public static string Encherir {
            get {
                return ResourceManager.GetString("Encherir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiquez votre courriel.
        /// </summary>
        public static string entrerCourriel {
            get {
                return ResourceManager.GetString("entrerCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiquez votre numero.
        /// </summary>
        public static string entrerNr {
            get {
                return ResourceManager.GetString("entrerNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Vente.
        /// </summary>
        public static string EnVent {
            get {
                return ResourceManager.GetString("EnVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string Envoyer {
            get {
                return ResourceManager.GetString("Envoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir supprimer cette catégorie.
        /// </summary>
        public static string Êtesvouscatégorie {
            get {
                return ResourceManager.GetString("Êtesvouscatégorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir supprimer le compte de ce membre.
        /// </summary>
        public static string Êtesvousmembre {
            get {
                return ResourceManager.GetString("Êtesvousmembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluations du membre.
        /// </summary>
        public static string Evaluationsdumembre {
            get {
                return ResourceManager.GetString("Evaluationsdumembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion Enchères.
        /// </summary>
        public static string GestionEncheres {
            get {
                return ResourceManager.GetString("GestionEncheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des objets.
        /// </summary>
        public static string gestobj {
            get {
                return ResourceManager.GetString("gestobj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id du membre.
        /// </summary>
        public static string Iddumembre {
            get {
                return ResourceManager.GetString("Iddumembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdMembre.
        /// </summary>
        public static string IdMembre {
            get {
                return ResourceManager.GetString("IdMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer le rapport.
        /// </summary>
        public static string Imprimerrapport {
            get {
                return ResourceManager.GetString("Imprimerrapport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;inscription.
        /// </summary>
        public static string Inscription {
            get {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string Inscriptionsite {
            get {
                return ResourceManager.GetString("Inscriptionsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste Des Évaluations Des Membres.
        /// </summary>
        public static string ListeDesÉvaluationsDesMembres {
            get {
                return ResourceManager.GetString("ListeDesÉvaluationsDesMembres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des objets.
        /// </summary>
        public static string Listedesobjets {
            get {
                return ResourceManager.GetString("Listedesobjets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste Membres Inscrits.
        /// </summary>
        public static string ListeMembresInscrits {
            get {
                return ResourceManager.GetString("ListeMembresInscrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste Objets Vendus Sous Peu.
        /// </summary>
        public static string ListeObjetsVendusSousPeu {
            get {
                return ResourceManager.GetString("ListeObjetsVendusSousPeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister echères perdus.
        /// </summary>
        public static string Listerecheresperdus {
            get {
                return ResourceManager.GetString("Listerecheresperdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister enchères encherits.
        /// </summary>
        public static string Listerencheresencherits {
            get {
                return ResourceManager.GetString("Listerencheresencherits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister enchères en cours.
        /// </summary>
        public static string Listerencheresencours {
            get {
                return ResourceManager.GetString("Listerencheresencours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister mes objets vendus - pdf.
        /// </summary>
        public static string Listermesobjetsvenduspdf {
            get {
                return ResourceManager.GetString("Listermesobjetsvenduspdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister objets achetés.
        /// </summary>
        public static string Listerobjetsachetes {
            get {
                return ResourceManager.GetString("Listerobjetsachetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister objets vendus.
        /// </summary>
        public static string Listerobjetsvendus {
            get {
                return ResourceManager.GetString("Listerobjetsvendus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister produits qui m&apos;ont intéressés - pdf.
        /// </summary>
        public static string Listerproduitsinteressepdf {
            get {
                return ResourceManager.GetString("Listerproduitsinteressepdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste utilisateurs.
        /// </summary>
        public static string ListeUsers {
            get {
                return ResourceManager.GetString("ListeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce n&apos;est pas le bon format de telephone!.
        /// </summary>
        public static string mauvaisformattel {
            get {
                return ResourceManager.GetString("mauvaisformattel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier profil.
        /// </summary>
        public static string mdfprofil {
            get {
                return ResourceManager.GetString("mdfprofil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MDP {
            get {
                return ResourceManager.GetString("MDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe et la confirmation ne correspondent pas..
        /// </summary>
        public static string MDPCONFIRMDIFFERENT {
            get {
                return ResourceManager.GetString("MDPCONFIRMDIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit compter minimum 6 caractères et maximum 50!.
        /// </summary>
        public static string MDPminmax {
            get {
                return ResourceManager.GetString("MDPminmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe est requis.
        /// </summary>
        public static string MDPrequis {
            get {
                return ResourceManager.GetString("MDPrequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes objets.
        /// </summary>
        public static string Mesobjets {
            get {
                return ResourceManager.GetString("Mesobjets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes objets en vente.
        /// </summary>
        public static string Mesobjetsenvente {
            get {
                return ResourceManager.GetString("Mesobjetsenvente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre En Vente.
        /// </summary>
        public static string MettreEnVente {
            get {
                return ResourceManager.GetString("MettreEnVente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Informations Profil.
        /// </summary>
        public static string ModifierInformationsProfil {
            get {
                return ResourceManager.GetString("ModifierInformationsProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mot de passe.
        /// </summary>
        public static string ModifierMDP {
            get {
                return ResourceManager.GetString("ModifierMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel utilisateur.
        /// </summary>
        public static string newuser {
            get {
                return ResourceManager.GetString("newuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de famille.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string nom2 {
            get {
                return ResourceManager.GetString("nom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        public static string Nouveau {
            get {
                return ResourceManager.GetString("Nouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle enchère.
        /// </summary>
        public static string Nouvelenchere {
            get {
                return ResourceManager.GetString("Nouvelenchere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle categorie.
        /// </summary>
        public static string Nouvellecategorie {
            get {
                return ResourceManager.GetString("Nouvellecategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle Evaluation.
        /// </summary>
        public static string Nouvellevaluation {
            get {
                return ResourceManager.GetString("Nouvellevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        public static string Numéro {
            get {
                return ResourceManager.GetString("Numéro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objets qui m&apos;ont intéressés.
        /// </summary>
        public static string Objetsintéressés {
            get {
                return ResourceManager.GetString("Objetsintéressés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Commission.
        /// </summary>
        public static string PageCommission {
            get {
                return ResourceManager.GetString("PageCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Rapports.
        /// </summary>
        public static string PageRapports {
            get {
                return ResourceManager.GetString("PageRapports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string Prix {
            get {
                return ResourceManager.GetString("Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Actuel.
        /// </summary>
        public static string PrixActuel {
            get {
                return ResourceManager.GetString("PrixActuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Départ.
        /// </summary>
        public static string PrixDepart {
            get {
                return ResourceManager.GetString("PrixDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix proposé.
        /// </summary>
        public static string Prixpropose {
            get {
                return ResourceManager.GetString("Prixpropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        public static string Rapports {
            get {
                return ResourceManager.GetString("Rapports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport sur la cote des membres.
        /// </summary>
        public static string Rapportsurlacotedesmembres {
            get {
                return ResourceManager.GetString("Rapportsurlacotedesmembres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport sur la synthese de vente annuelle.
        /// </summary>
        public static string Rapportsursynthesevente {
            get {
                return ResourceManager.GetString("Rapportsursynthesevente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récuperation du nouveau mot de passe.
        /// </summary>
        public static string Récuperationmot {
            get {
                return ResourceManager.GetString("Récuperationmot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sujet.
        /// </summary>
        public static string Sujet {
            get {
                return ResourceManager.GetString("Sujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthèse Ventes Annuelles.
        /// </summary>
        public static string SynthèseVentesAnnuelles {
            get {
                return ResourceManager.GetString("SynthèseVentesAnnuelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchager.
        /// </summary>
        public static string Telechager {
            get {
                return ResourceManager.GetString("Telechager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to télécharger la pièce jointe.
        /// </summary>
        public static string telechargerlapiecejointe {
            get {
                return ResourceManager.GetString("telechargerlapiecejointe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string Téléphone {
            get {
                return ResourceManager.GetString("Téléphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Ventes.
        /// </summary>
        public static string TotalVentes {
            get {
                return ResourceManager.GetString("TotalVentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les membres inscrits.
        /// </summary>
        public static string Touslesmembresinscrits {
            get {
                return ResourceManager.GetString("Touslesmembresinscrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendeur.
        /// </summary>
        public static string Vendeur {
            get {
                return ResourceManager.GetString("Vendeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventes echus ou sous peu echus - pdf.
        /// </summary>
        public static string Ventesechusousouspeuechuspdf {
            get {
                return ResourceManager.GetString("Ventesechusousouspeuechuspdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir Evaluation.
        /// </summary>
        public static string VoirEvaluation {
            get {
                return ResourceManager.GetString("VoirEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone administration.
        /// </summary>
        public static string Zoneadministration {
            get {
                return ResourceManager.GetString("Zoneadministration", resourceCulture);
            }
        }
    }
}
